language: go

go:
    - '1.13'
    - 'tip'

install:
    - make install-tools

script:
    - make ci-check

after_success:
    - test $TRAVIS_GO_VERSION != 'tip' && bash <(curl -s https://codecov.io/bash)
