language: go

go:
    - '1.13'
    - '1.x'

install:
    - make install-tools

script:
    - make ci-check
    - goveralls -coverprofile=coverage-all.out

after_success:
    - bash <(curl -s https://codecov.io/bash)
